Restructured bottles of beer recursive example
drewesk/learning_by_doing pull request #16
Opened 2016-10-16 05:07 UTC by drewesk

* Changed structure of song to better match the pauses of singing the song

* Made my base_case def last in order to avoid hoisting

* Var names differ

[#131780287]

2016-10-16 21:14 UTC, jasonnoble requested changes

2016-10-16 21:14 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +def base_case(bottles)
Wouldn't a better name be `sing_verse`?

2016-10-16 21:14 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +  puts bottle_of_beer + ' on the wall, ' + bottle_of_beer + '.'
Does `puts "#{plural(bottles, 'bottle') of beer"` not work?

2016-10-16 21:14 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +  puts bottle_of_beer + ' on the wall, ' + bottle_of_beer + '.'
Oh, I see what you did...  Carry on. :)

2016-10-19 06:20 UTC, drewesk commented on methods_and_recursion/bottles_of_beer.rb
> +  puts bottle_of_beer + ' on the wall, ' + bottle_of_beer + '.'
Damn rubocop putting on the shackles!

2016-10-22 01:30 UTC, jasonnoble requested changes

2016-10-22 01:30 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +  puts 'No more bottles of beer on the wall, no more bottles of beer.'
So, on line 23, you check to see if bottles > 1, if it's not, i.e. it's the last bottle, you call `no_bottles_left`.  Which means you don't need the if check on line 5...

2016-10-25 03:13 UTC, jasonnoble approved these changes

2016-10-25 03:14 UTC, merged