Updated the variables in the number_of_seconds.rb
drewesk/learning_by_doing pull request #6
Opened 2016-10-09 07:20 UTC by drewesk

* Implemented the changes requested

[#131780275]

2016-10-10 02:41 UTC, jasonnoble commented on numbers_letters_and_variables/number_of_seconds.rb
> +puts "  #{seconds_in_a_minute * minutes_in_a_hour} seconds in an hour,"
Could you pull out a `seconds_in_a_hour` variable above?  IMO, I like to have interpolation do as little calculation as possible...

2016-10-10 02:41 UTC, jasonnoble commented on numbers_letters_and_variables/number_of_seconds.rb
> +puts "  #{seconds_in_a_minute * minutes_in_a_hour * hours_in_a_day} seconds in a day,"
`seconds_in_a_day`

2016-10-10 02:42 UTC, jasonnoble commented on numbers_letters_and_variables/number_of_seconds.rb
> +puts "  #{seconds_in_a_minute * minutes_in_a_hour * hours_in_a_day * days_in_a_week} seconds in a week"
`seconds_in_a_week`

2016-10-10 03:44 UTC, drewesk reviewed
[#131780275]

2016-10-16 20:41 UTC, jasonnoble requested changes

2016-10-16 20:41 UTC, jasonnoble commented on numbers_letters_and_variables/number_of_seconds.rb
> +seconds_in_day = seconds_in_a_minute * minutes_in_a_hour * hours_in_a_day
seconds_in_hour = seconds_in_a_minute * minutes_in_a_hour
    seconds_in_day = seconds_in_hour * hours_in_a_day
    seconds_in_week = seconds_in_day * days_in_a_week
    seconds_in_year = seconds_in_day * days_in_a_year
    age_twenty = (seconds_in_year * 20)
    age_hundred = (seconds_in_year * 100)

2016-10-17 06:06 UTC, closed without merging